### ISSUE TITLE
[Suggestion] ES6 Support for Iron:router

### ISSUE THREAD

**Issue by kenshinman** [veliovgroup/jazeee-meteor-spiderable#54]
Will there be an upgrade soon to support routers that use ES6

Been having issues with iron router showing the 'Splash Screen' and on investigation (thanks to @dr-dimitru for the help too), It turned out that the problem was because it didn't support es6.

**Comment by dr-dimitru** [comment]
Hello @kenshinman ,

 1. This is not Iron:router issue. It's Meteor's issue as it doesn't transpiles NPM modules written in ES6
 2. This issue is widely discussed in #50 , take a look at it
 3. Suggestion to move from phantomjs to other rendering solution is in #51 , while it's reasonable we haven't found an easy way to do so in terms of one package, nor found stable enough solution.

Closing this one in favor of #51 
Feel free to reopen it in case if the issue still persists on your end.
